AdguardTeam/AdguardBrowserExtension

Compiler/build.sh

Add checks to the build.sh

---

Extension/lib/utils/frames.js

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/172

---

Extension/tests/css-filter/test-css-filter.js

Fix #343 css hits unit tests

---

Extension/lib/filter/rules/css-filter-rule.js
Extension/tests/css-filter/test-css-filter.js

#342 fix pseudo class parsing

---

Extension/browser/chrome/lib/content-script/websocket.js

#349 websocket wrapper

---

Extension/browser/chrome/lib/content-script/websocket.js
Extension/browser/webkit/webrequest.js
Extension/lib/content-script/preload.js

Handles two issues:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/346
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/355
Also improves this one:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/301

Minor fixes

---

Extension/browser/safari/lib/content-blocker-listener.js
Extension/browser/safari/lib/content-blocker.js
Extension/browser/safari/lib/converter.js
Extension/lib/filter/rules/base-filter-rule.js
Extension/lib/filter/rules/filter-rule-builder.js

Fix for this issue
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/360

Content blocker fix

---

Extension/browser/firefox/lib/contentPolicy.js
Extension/browser/safari/lib/converter.js
Extension/lib/filter/filtering-log.js
Extension/lib/filter/request-blocking.js
Extension/lib/filter/rules/url-filter-rule.js
Extension/lib/pages/log.js
Extension/lib/utils/common.js
Extension/pages/log.html
Extension/pages/skin/style.css
Extension/tests/safari-converter/test-safari-converter.js
Extension/tests/url-filter/test-url-filter.js

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/370

---

Extension/lib/filter/rules/base-filter-rule.js
Extension/tests/css-filter/test-css-filter.js

Fix #391 clean up restricted-permitted domain

---

Extension/browser/chrome/manifest.json
Extension/browser/edge/manifest.json
Extension/browser/firefox/lib/contentScripts.js
Extension/browser/safari/Info.plist
Extension/lib/content-script/preload.js
Extension/lib/utils/element-collapser.js
Extension/tests/miscellaneous/test-csp-utils.html
Extension/tests/miscellaneous/test-element-collapser.html
Extension/tests/miscellaneous/test-element-collapser.js

Fix #366 element collapser

---

Extension/browser/webkit/lib/utils/csp-utils.js
Extension/browser/webkit/prefs.js
Extension/browser/webkit/webrequest.js

#385 csp connect-src

---

Compiler/build.sh
Compiler/src/main/java/com/adguard/compiler/Main.java
Compiler/src/main/java/com/adguard/compiler/SettingUtils.java

#388 Support remote script rules for non-amo FF

---

Extension/browser/safari/lib/converter.js
Extension/lib/filter/rules/url-filter-rule.js
Extension/tests/safari-converter/test-safari-converter.js

#406 fix cyrillic rules domain parsing

---

Extension/lib/content-script/preload.js

#320 Protecting styles

---

Extension/browser/firefox/lib/contentPolicy.js
Extension/browser/firefox/lib/tabsMap.js

#416 FF websockets fix

---

Extension/lib/filter/rules/url-filter-rule.js
Extension/tests/url-filter/test-url-filter.js

#332 Regexp rules shortcut

---

Extension/browser/firefox/lib/contentScripts.js

#380 unload frame script on extension update

#380 hot fix FF

---

Extension/browser/safari/lib/converter.js
Extension/tests/safari-converter/safari-correct-rules.js
Extension/tests/safari-converter/test-safari-converter.js

#437 Safari converter generichide

---

Extension/browser/webkit/webrequest.js

#440 fix iframes CSP

---

Extension/browser/chrome/blockpopup.js
Extension/browser/firefox/lib/contentPolicy.js
Extension/browser/webkit/webrequest.js
Extension/lib/filter/request-blocking.js
Extension/lib/utils/frames.js

#444 frames referrer issues

---

Extension/browser/firefox/data/content/content-script/frame-script.js

#446 FF frame script loading

---

Extension/lib/content-script/preload.js

Fix #467 collapse exceptions

---

Extension/browser/chrome/lib/content-script/devtools-helper.js
Extension/browser/chrome/lib/pages/devtools-elements-sidebar.js
Extension/browser/chrome/manifest.json
Extension/browser/chrome/pages/devtools-elements-sidebar.html
Extension/lib/content-script/assistant/js/adguard-rules-constructor.js
Extension/lib/content-script/assistant/js/assistant.js
Extension/lib/libs/dom.patched.js
Extension/lib/libs/sources.txt
Extension/tests/rule-constructor/test-rule-constructor.html
Extension/tests/rule-constructor/test-rule-constructor.js

Fix #386 svg elements className

---

Extension/browser/chrome/lib/background-page.js
Extension/browser/chrome/manifest.json
Extension/browser/edge/manifest.json
Extension/browser/webkit/ui.js
Extension/browser/webkit/webrequest.js
Extension/lib/filter/request-blocking.js

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/477

Resolved issues with insider preview build

---

Extension/browser/chrome/lib/pages/devtools-elements-sidebar.js
Extension/lib/content-script/assistant/js/adguard-rules-constructor.js

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/483

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/483

---

Extension/browser/safari/lib/converter.js
Extension/lib/filter/rules/url-filter-rule.js
Extension/tests/safari-converter/test-safari-converter.js

Fix #510 safari converter

---

Extension/lib/filter/rules/domains-lookup-table.js
Extension/lib/filter/rules/shortcuts-lookup-table.js
Extension/tests/url-filter/test-url-filter.js

#514 rules duplicates in DomainsLookupTable

---

Extension/browser/chrome/lib/api/background-page.js
Extension/browser/chrome/lib/api/tabs.js
Extension/browser/firefox/lib/api/webrequest-api.js
Extension/browser/safari/lib/api/background-page.js
Extension/lib/content-message-handler.js
Extension/lib/content-script/preload.js
Extension/lib/filter/request-blocking.js
Extension/lib/tabs/tabs-api.js
Extension/lib/webrequest.js

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/512

#512 Execute js rules as soon as possible

---

Extension/browser/chrome/lib/api/background-page.js
Extension/browser/firefox/lib/api/webrequest-api.js
Extension/browser/safari/lib/api/background-page.js
Extension/lib/filter/request-blocking.js
Extension/lib/filter/rules/url-filter-rule.js
Extension/lib/utils/common.js
Extension/lib/webrequest.js

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/280

#280 $empty modifier

---

Extension/browser/safari/lib/converter.js
Extension/tests/safari-converter/safari-correct-rules.js
Extension/tests/safari-converter/test-safari-converter.js

Fix #507 safari converter generichide

---

Extension/browser/chrome/manifest.json
Extension/browser/edge/manifest.json
Extension/browser/firefox/lib/contentScripts.js

Add filterlists.com to possible filters sources #544

---

Extension/pages/skin/my.css

A phrase is clipped in Russian localization #538

---

Extension/lib/ui-service.js

Feature request - another filtering log performance. #403

---

Extension/lib/filter/rules/url-filter-rule.js
Extension/tests/url-filter/test-url-filter.js

Regular expressions with $ aren't processed properly #517

---

Compiler/src/main/java/com/adguard/compiler/FilterUtils.java
Compiler/src/main/java/com/adguard/compiler/Main.java
Compiler/src/main/java/com/adguard/compiler/ScriptRules.java
Compiler/src/main/java/com/adguard/compiler/SettingUtils.java
Extension/browser/firefox/lib/prefs.js
Extension/browser/webkit/prefs.js
Extension/filters/chromium/local_script_rules.json
Extension/filters/firefox/local_script_rules.json
Extension/filters/safari/local_script_rules.json
Extension/lib/filter/rules/script-filter-rule.js
Extension/lib/filter/subscription.js
Extension/lib/utils/local-script-rules.js
Extension/lib/utils/promises.js
Extension/lib/utils/service-client.js

Change local-script-rules.js, make it a .json file instead #554

---

Extension/lib/filter/rules/url-filter-rule.js
Extension/tests/url-filter/test-url-filter.js

#559 Fix ampersand in options

---

Extension/lib/filter/rules/simple-regex.js
Extension/lib/filter/rules/url-filter-rule.js
Extension/tests/url-filter/test-url-filter.js

#556 
All changes in master reverted and moved to this branch.

Fix #556 regexp any symbol

---

Extension/lib/filter/rules/css-filter-rule.js
Extension/tests/css-filter/test-css-filter.js

#576 Parsing pseudo

---

Extension/lib/filter/safebrowsing-filter.js

#583 fix safebrowsing

---

Extension/browser/chrome/lib/api/tabs.js

Browsing security doesn't work #580

---

Extension/browser/chrome/lib/api/background-page.js
Extension/browser/firefox/lib/api/webrequest-api.js
Extension/lib/blockpopup.js
Extension/lib/content-script/preload.js
Extension/lib/utils/url.js
Extension/lib/webrequest.js

chrome.webRequest.onBeforeRequest now intercepts WebSocket #572

---

Extension/browser/firefox/lib/api/webrequest-api.js
Extension/lib/blockpopup.js
Extension/lib/utils/url.js
Extension/lib/webrequest.js

Block `blob:` URLs #525

---

Extension/lib/webrequest.js

Basic URL rule, which contains domain name, blocks WS #528

---

Extension/browser/safari/lib/converter.js
Extension/tests/safari-converter/test-safari-converter.js

$websocket modifier works incorrectly in Safari

---

Extension/browser/firefox/lib/api/webrequest-api.js
Extension/lib/webrequest.js

Content Security Policy checks

---

Extension/browser/chrome/lib/api/background-page.js
Extension/browser/chrome/lib/api/tabs.js
Extension/browser/edge/lib/utils/rules-storage.js
Extension/browser/webkit/lib/prefs.js
Extension/lib/filter/request-blocking.js
Extension/lib/filter/update-service.js
Extension/lib/utils/browser-utils.js
Extension/lib/webrequest.js

Edge Insider Preview issues (CSP, storage.local)

---

Extension/browser/firefox/install.rdf
Extension/lib/filter/integration.js
Extension/lib/utils/browser-utils.js

Integration mode is broken in Firefox #607

---

Extension/lib/filter/rules/css-filter-rule.js
Extension/tests/css-filter/test-css-filter.js

#617 fix css rules parsing

---

Extension/lib/content-script/preload.js

Adguard forum - problem with avatar #497
This fix doesn't fully resolve the problem because we are still injecting CSS into the DOM in the case of FF browser.

Cleanup scripts after execution

---

Extension/browser/chrome/lib/api/tabs.js
Extension/browser/firefox/lib/api/tabs.js
Extension/browser/safari/lib/api/tabs.js
Extension/lib/tabs/tabs-api.js

Browsing security - "Proceed anyway" issue #628

---

Extension/browser/safari/lib/converter.js

WS blocking issue (Safari) #586

---

Extension/lib/pages/options.js

Huge user filter slows down the "options" page loading #641

---

Extension/lib/content-script/assistant/js/assistant.js

Fix #647 assistant style

---

Compiler/build.sh
Compiler/src/main/java/com/adguard/compiler/Main.java
Compiler/src/main/java/com/adguard/compiler/SettingUtils.java
Extension/api/chrome/manifest.json
Extension/browser/chrome/lib/api/background-page.js
Extension/browser/chrome/manifest.json
Extension/browser/edge/manifest.json
Extension/browser/firefox_webext/manifest.json

Adguard 2.6.1 Beta does not block WebSocket connection #652

---

Extension/lib/filter/locale-detect.js

#666 Fix filters autodetect integration

---

Extension/lib/content-script/wrappers.js
Extension/lib/pages/log.js

$webrtc does not work on rapidvideo.com #669

---

Extension/browser/chrome/lib/utils/local-storage.js
Extension/browser/edge/lib/utils/rules-storage.js
Extension/browser/firefox_webext/lib/start.js
Extension/lib/filter/update-service.js
Extension/lib/startup.js
Extension/lib/storage.js
Extension/lib/utils/common.js

Cleaning Firefox data breaks Adguard extension #681

---

Extension/lib/content-script/assistant/js/start-assistant.js
Extension/lib/content-script/content-utils.js
Extension/lib/content-script/preload.js

Errors in FF browser console #673

---

Extension/browser/edge/manifest.json

#691 
Revert: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/652

#691 Fix edge assistant style

---

Extension/api/chrome/background.html
Extension/browser/chrome/background.html
Extension/browser/firefox/background.html
Extension/browser/firefox_webext/background.html
Extension/browser/safari/background.html
Extension/browser/safari/lib/converter.js
Extension/lib/filter/antibanner.js
Extension/lib/filter/filtering-log.js
Extension/lib/filter/filters.js
Extension/lib/filter/request-blocking.js
Extension/lib/filter/rules/csp-filter.js
Extension/lib/filter/rules/url-filter-lookup-table.js
Extension/lib/filter/rules/url-filter-rule.js
Extension/lib/pages/log.js
Extension/lib/utils/common.js
Extension/lib/webrequest.js
Extension/pages/log.html
Extension/tests/request-filter/test-request-filter.html
Extension/tests/request-filter/test-request-filter.js

Add $csp modifier support #685

---

Extension/lib/content-script/preload.js
Extension/lib/content-script/wrappers.js

WebRTC contentWindow circumvention #588

---

Extension/lib/ui-service.js

#672 small fix

---

Extension/_locales/en/messages.json
Extension/lib/pages/log.js
Extension/pages/log.html

#626 adding rule dialog important option

---

Extension/browser/chrome/lib/api/tabs.js

Filtering log: new tab stays in the background when opened #697

---

Extension/lib/libs/css.escape.js

"Block ads on this website" tool does not work in Safari 9.1.3 #704

---

Extension/browser/safari/lib/converter.js
Extension/lib/filter/antibanner.js
Extension/lib/filter/filters.js
Extension/lib/filter/request-blocking.js
Extension/lib/filter/rules/csp-filter.js
Extension/lib/filter/rules/url-filter-rule.js
Extension/lib/webrequest.js
Extension/tests/request-filter/test-request-filter.js

Forbidden CSP directives. #685

Forbidden CSP directives

---

Extension/browser/chrome/lib/pages/devtools-elements-sidebar.js
Extension/browser/chrome/pages/devtools-elements-sidebar.html

Fix #703 dev-tools select all attributes

---

Extension/lib/content-script/preload.js

Google docs are broken in Adguard Edge extension #720

---

Extension/lib/filter/request-blocking.js
Extension/lib/webrequest.js

CSP and WebRTC rules aren't processed properly

---

Extension/lib/filter/rules/url-filter-rule.js
Extension/tests/url-filter/test-url-filter.js

Fix #719 content option rules

---

Extension/pages/skin/logpage/css/style.css

Scrollbar is missing in the filtering log #732

---

Extension/lib/filter/rules/url-filter-rule.js
Extension/tests/url-filter/test-url-filter.js

#719 back to basic impelementation

#719 content option rules

---

Extension/lib/webrequest.js

Fix #748 behaviorChanged events

---

Compiler/build.sh
Compiler/src/main/java/com/adguard/compiler/Browser.java
Extension/lib/utils/service-client.js

https://github.com/AdguardTeam/AdguardFilters/issues/5488

Opera platform url

---

Extension/lib/content-script/preload.js

AdGuard causes browser crash on some pages #770

---

Extension/browser/firefox/lib/api/tabs.js

Incorrect work on Pale Moon v26.5 (WinXP) #773

---

Extension/browser/chrome/lib/api/background-page.js

Requests with PING type aren't processed

---

Extension/lib/content-script/preload.js

Fix #779 svg prehide

---

Extension/pages/css/style-settings.css
Extension/pages/options.html

feature/788 settings-fix

---

Extension/api/chrome/manifest.json
Extension/browser/chrome/manifest.json
Extension/browser/edge/manifest.json
Extension/browser/firefox/lib/contentScripts.js
Extension/browser/firefox_webext/manifest.json
Extension/browser/safari/Info.plist
Extension/lib/libs/extended-css.js
Extension/tests/css-filter/test-css-hits.html

#771 updated extended-css library

---

Extension/lib/content-script/assistant/js/adguard-selector.js

Fix #818 selector scrolling

---

Extension/lib/libs/dom.patched.js

Fix #786 dom prediction helper

---

Extension/lib/filter/rules/css-filter-rule.js

#771 extended css validation
